# docker-compose.yml
version: '3.8'

services:
  flask:
    build:
      context: .
    volumes:
      - ./dataset:/app/dataset
      - ./flower_classification_model.h5:/app/flower_classification_model.h5
    expose:
      - "5000:5000"
    environment:
      FLASK_ENV: development

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - flask
